language: node_js

node_js:
  node

branches:
  only:
    - master
    - dev

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      env: JOB="Build"
      script: npm run build

    - stage: test
      env: JOB="Mocha unit tests"
      script: 
        - npm run test-1
        - npm run test-2
        - npm run test-3
      after_success:
        - npm run coverage

    - stage: test
      env: JOB="Tslint"
      script: npm run tslint

    - stage: test
      if: NOT fork
      env: JOB="Tests with real-world data"
      script:  npm run test-3
        
