language: node_js

node_js:
  node

branches:
  only:
    - master
    - dev

stages:
  - build
  - test

jobs:
  include:
    # - env:
    #   if: NOT branch = master
    #   - NODE_ENV=development
    - env:
      - NODE_ENV=production

    - stage: build
      script: npm run build

    - stage: test
      env: JOB="Mocha unit tests"
      script: 
        - npm run test-1
        - npm run test-2
      after_success:
        - npm run coverage

    - stage: test
      env: JOB="Tslint"
      script: npm run tslint

    - stage: test
      env: JOB="Tests with real-world data"
      if: NOT type = pull_request
      script:
      - npm run test-3
        
