language: node_js

node_js:
  node

branches:
  only:
    - master
    - dev

stages:
  - build
  - test
  - tslint

jobs:
  include:
    - stage: build
      script: npm run build

    - stage: test
      script: 
        - npm run test-1
        - npm run test-2

    - stage: test
      if: NOT type = pull_request
      script:
      - npm run test-3
    
    - stage: tslint
      script: npm run tslint
        
