language: node_js

branches:
  only:
    - master
    - dev

node_js:
  node

# matrix:
#   include:
#   - script:
#     - npm run test-1
#   - script:
#     - npm run test-2

jobs:
  include:
  - script:
    - npm run test-1
  - script:
    - npm run test-2


jobs:
  include:
    - if: NOT fork
      script:
      - npm run test-3
